name: CI/CD Frontend Phoenix Orders

on:
  push:
    branches: [ main, "feature/**" ]

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Frontend
        run: npm run build

      - name: Subir Artifact
        uses: actions/upload-artifact@v4
        with:
          name: phoenix-orders-frontend
          path: dist/
          retention-days: 14
  
  deploy-dev:
    name: Deploy a DEV (EC2)
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    environment:
      name: DEV

    steps:
      - name: Descargar Artifact
        uses: actions/download-artifact@v4
        with:
          name: phoenix-orders-frontend
          path: dist

      - name: Limpiar directorio DEV en el servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/frontend
            sudo chown -R $USER:$USER /var/www/frontend

            rm -rf /var/www/frontend/*
            rm -rf /var/www/frontend/.[!.]* 2>/dev/null || true

            echo "Directorio /var/www/frontend preparado correctamente."

      - name: Copiar archivos al servidor EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/**"
          target: "/var/www/frontend"
          strip_components: 1
          rm: false
